create table if not exists public.competitors (
  id bigint generated by default as identity primary key,
  name text not null,
  url text,
  remarks text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists competitors_created_at_idx
  on public.competitors (created_at desc);
