create table if not exists public.competitors (
  id bigint generated by default as identity primary key,
  name text not null,
  url text,
  remarks text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists competitors_created_at_idx
  on public.competitors (created_at desc);

create table if not exists public.monitor_snapshots (
  id bigint generated by default as identity primary key,
  competitor_id bigint not null references public.competitors(id) on delete cascade,
  fingerprint text not null,
  data jsonb not null,
  comparable_data jsonb not null,
  captured_at timestamptz not null default now()
);

create index if not exists monitor_snapshots_competitor_captured_idx
  on public.monitor_snapshots (competitor_id, captured_at desc);

create table if not exists public.change_events (
  id bigint generated by default as identity primary key,
  competitor_id bigint not null references public.competitors(id) on delete cascade,
  competitor_name text not null,
  url text,
  changed_fields text[] not null default '{}',
  change_details jsonb not null default '[]'::jsonb,
  detected_at timestamptz not null default now()
);

create index if not exists change_events_detected_at_idx
  on public.change_events (detected_at desc);

create index if not exists change_events_competitor_detected_idx
  on public.change_events (competitor_id, detected_at desc);
